services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    environment:
      - 'MYSQL_DATABASE=ecommerce'
      - 'MYSQL_PASSWORD=HoangSon1603'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user1'
    ports:
      - '3306:3306'
  app:
    image: 'spring-ecommerce:latest'
    build:
      dockerfile: './nhs-app/Dockerfile'
      context: './nhs-app'
    environment:
      HOST: 'mysql'
      PORT: '3306'
      DATABASE: 'ecommerce'
    working_dir: '/nhs-app'
    command: './mvnw spring-boot:run'
    depends_on:
      - mysql
    ports:
      - 8086:8086
