spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/ecommerce?createDatabaseIfNotExist=true
    password:
  security:
    oauth2:
          client:
            registration:
              google:
                client-id: "164335260283-p34snad9i8k1chtgrsg3ji0ragptluul.apps.googleusercontent.com"
                client-secret: "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"
                authorization-grant-type: authorization_code
                scope:
                  - email
                  - profile
payment:
  zalo:
    appid: 2553
    key1: PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
    key2: Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3
    endpoint:
      create: https://sb-openapi.zalopay.vn/v2/create
      query: https://sb-openapi.zalopay.vn/v2/query
  vnpay:
    version: 2.1.0
    payurl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnurl: /vnpay-payment
    apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    tmnCode: "CTTVNP01" #    default tmncode is ""
    vnp_HashSecret: "hgkdgkd"
server:
  port: 8085